name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  build-suite:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ceph_version:
        - "luminous"
    steps:
      - name: Install Ceph dependency
        run: |
          sudo wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
          sudo echo deb https://download.ceph.com/debian-${{ matrix.ceph_version }}/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
          sudo apt-get update
          sudo apt-get install -y libcephfs-dev librbd-dev librados-dev

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run go fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run go vet
        run: go vet -tags ${{ matrix.ceph_version }} ./...

      - name: Test
        run: go test -tags ${{ matrix.ceph_version }}  -v .

      - name: Build
        run: |
          go build -tags ${{ matrix.ceph_version }} -o cephfs-xattr-influx main.go
          tar -czvf cephfs-xattr-influx.${{ matrix.ceph_version }}.tar.gz cephfs-xattr-influx

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: cephfs-xattr-influx.${{ matrix.ceph_version }}.tar.gz
          asset_name: cephfs-xattr-influx-${{ matrix.ceph_version }}-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip