name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-suite:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ceph_version:
        - "luminous"
    steps:
      - name: Install Ceph dependency
        run: |
          sudo echo deb https://download.ceph.com/debian-${{ matrix.ceph_version }}/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
          sudo apt-get update
          sudo apt-get install -y libcephfs-dev librbd-dev librados-dev

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run go fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run go vet
        run: go vet ./...

      - name: Test
        run: go test -v .
